import React from 'react';
import {
  Bookmark,
  Home,
  HomeFill,
  Explore,
  Lists,
  Messages,
  More,
  Notification,
  Profile,
  ProfileFill,
  Twitter,
  ExplorerFill,
  NotificationFill,
  MessagesFill,
  BookmarkFill,
  ListsFill,
} from '../../components/icons';

export const MENU = [
  {
    key: 'twitter',
    path: '/',
    Icon: <Twitter style={{ fontSize: 30, color: 'white' }} />,
    IconSelected: <Twitter style={{ fontSize: 30, color: 'white' }} />,
    title: '',
  },
  {
    key: 'home',
    path: '/',
    Icon: <Home />,
    IconSelected: <HomeFill />,
    title: 'Home',
  },
  {
    key: 'explore',
    path: '/explore',
    Icon: <Explore />,
    IconSelected: <ExplorerFill />,
    title: 'Explore',
  },
  {
    key: 'notifications',
    path: '/notifications',
    Icon: <Notification />,
    IconSelected: <NotificationFill />,
    title: 'Notifications',
    notify: 17,
  },
  {
    key: 'messages',
    path: '/messages',
    Icon: <Messages />,
    IconSelected: <MessagesFill />,
    title: 'Messages',
  },
  {
    key: 'bookmarks',
    path: '/bookmarks',
    Icon: <Bookmark />,
    IconSelected: <BookmarkFill />,
    title: 'Bookmarks',
  },
  {
    key: 'lists',
    path: '/lists',
    Icon: <Lists />,
    IconSelected: <ListsFill />,
    title: 'Lists',
  },
  {
    key: 'profile',
    path: '/profile',
    Icon: <Profile />,
    IconSelected: <ProfileFill />,
    title: 'Profile',
  },
  {
    key: 'more',
    path: '/more',
    Icon: <More />,
    IconSelected: <More />,
    title: 'More',
  },
];
